name: amazing_booking_app
description: "A new Flutter project booking anything in the world"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_svg: ^2.0.16
  http: ^1.2.2
  dio: ^5.7.0
  flutter_dotenv: ^5.0.2
  fluttertoast: ^8.2.8
  flutter_typeahead: ^5.2.0
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  crypto: ^3.0.6
  convert: ^3.1.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.2.0
  location: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "app_icon.png"
  android_icon_size: 48
  background_color: "#ffffff"
flutter_lints: ^4.0.0

flutter:
  assets:
    - .env
    - assets/images/
    - assets/images/auth/
    - assets/images/top_location/

  uses-material-design: true
